name: Deploy Maintenance Page
on:
  workflow_dispatch:
jobs:
  deploy:
    environment:
      name: ${{ github.ref_name == 'main' && 'Production' || 'Staging' }}
    if: github.ref_name == 'main' || github.ref_name == 'staging'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ENV: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
        timeout-minutes: 3
      - name: Build
        id: build
        run: |
          pnpm assets
          pnpm --filter @allondeveen-portfolio/maintenance build
        env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        timeout-minutes: 3
      - name: Deploy
        run: "pnpm --filter @allondeveen-portfolio/maintenance run deploy"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        timeout-minutes: 5
